server:
  port: 10010
  #port: 80
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/**   #因此Zuul就提供了一种简化的配置语法：zuul.routes.<serviceId>=<path>
  ignored-services: upload-service #Zuul网关忽略上传模块

